name: codecov

on: [push, pull_request, workflow_dispatch]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install library
        run: pip install pandas pytest pytest-cov
      - name: Install pandaq
        run: pip install .
      - name: Run test
        run: pytest --cov=pandaq --cov-report=xml tests/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
